name: Code quality checks
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  qa:
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: phive
        run: ant getphive

      - name: phive install
        run: ant -Dphive.bin=./phive.phar install-tools

      - name: php-cs-fixer
        run: ant -Dphive.bin=./phive.phar php-cs-fixer

      - name: phpstan
        run: ant -Dphive.bin=./phive.phar phpstan

      - name: psalm
        run: ant -Dphive.bin=./phive.phar psalm
